config/routes.rb
Rails.application.routes.draw do
  get 'event_attendings/create'
  resources :events
  resources :static
  resources :sessions, only: %i[ destroy new create ]
  resources :users, only: %i[new create show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'sign_up', to: 'users#new', as: 'sign_up'
  get 'sign_in', to: 'sessions#new', as: 'sign_in'
  get 'sign_out', to: 'sessions#destroy', as: 'sign_out'

  root 'static#homepage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  scope :upcoming_events, -> { where('date >= ?', Date.today).order('date DESC') }
  scope :previous_events, -> { where('date < ?', Date.today).order('date DESC') }

  has_many :event_attendings, foreign_key: :event_id
  has_many :event_attendees, through: :event_attendings, source: :attendee
  belongs_to :creator, class_name: 'User'
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_events, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, presence: true

  has_many :event_attendings, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendings
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_signed_in?

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    current_user
  end
end

app/controllers/event_attendings_controller.rb
class EventAttendingsController < ApplicationController
  def create
    @event = Event.find(params[:id])

    if @event.event_attendees.include? current_user
      redirect_to event_path(@event), alert: 'You are already an attendee!'
    else
      @event.event_attendees << current_user
      redirect_to event_path(@event), notice: "Registered to attende the #{@event.title} event!!"
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events
  # GET /events.json
  def index
    @upcoming_events = Event.upcoming_events
    @previous_events = Event.previous_events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @attendees = @event.event_attendees
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        @attendee.each do |att|
          next if att.empty?

          @user = User.find(att)

          @event.event_attendees << @user unless @event.event_attendees.include?(@user)
        end

        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :venue, :description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(email: params[:email])

    if @user
      session[:user_id] = @user.id
      redirect_to @user, notice: 'You\'ve logged in successfully!'
    else
      flash.now[:alert] = 'Name or email is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Signed out Successfully!'
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
    @events = Event.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user
    @created_events = @user.created_events
    @previously_attended_events = current_user.attended_events.previous_events
    @upcoming_events = current_user.attended_events.upcoming_events
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'Signed up successfully!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendings_helper.rb
module EventAttendingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def edit_page(event)
    link_to 'Edit', edit_event_path(event) if current_user == @event.creator
  end

  def update_page(event)
    link_to 'Update', edit_event_path(event) if current_user == @event.creator
  end

  def destroy_event(event)
    link_to 'Destroy', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } if current_user == @event.creator
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendings/create.html.erb
<h1>EventAttendings#create</h1>
<p>Find me in app/views/event_attendings/create.html.erb</p>

app/views/events/_form.html.erb
<div class="container w-70 new_event">
  <%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :venue %>
      <%= form.text_field :venue, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= form.label :date %>
      <%= form.date_field :date, class: "form-control"  %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="container">
  <h1 class="text-info mx-3">Editing Event</h1>

  <%= render 'form', event: @event %>

  <%= link_to 'Show', @event, class: "btn btn-info mx-3 mt-2" %> |
  <%= link_to 'Back', events_path, class: "btn btn-info mx-3 mt-2" %>
</div>

app/views/events/index.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-sm">
      <h2 class="title">Showing upcoming events:</h2>

      <% Event.upcoming_events.each do |event| %>
        <ul>
          <li class="event text-info"><%= link_to event.title, event_path(event) %></li>
        </ul>
      <% end %>
    </div>

    <div class="col-sm">
      <h2>Previously attended events: </h2>

      <% Event.previous_events.each do |event| %>
        <ul>
          <li class="event text-info"><%= link_to event.title, event_path(event) %></li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container p-2 w-70">
  <h1 class="text-info mx-3">New Event</h1>

  <%= render 'form', event: @event %>

  <%= link_to 'Back', events_path, class: "btn btn-md btn-info mt-3 mx-3" %>

</div>

app/views/events/show.html.erb
<div class="container mt-5">
  <div class="card">
    <div class="card-header">
      <h2 class="card-title"><%= @event.title %></h2>
    </div>

    <div class="card-body">
      <p><%= @event.description %></p>
    </div>

    <div class="card-footer">
      <h5>Venue: <small class="text-info"><%= @event.venue %></small></h5>
      <h5>Date: <small class="text-info"><%= @event.date %></small></h5>
      <h5>Created by: <small class="text-info">@<%= @event.creator.name %></small></h5>

      <div class="control">
        <%= edit_page(@event)%>
        <%= update_page(@event)%>
        <%= destroy_event(@event)%>
        <%= link_to 'Back', events_path %>
      </div>
    </div>
  </div>

  <div class="attendees mt-4">
    <h3 class="title">People attending: </h3>
    <% @attendees.each do |event| %>
      <p class="mb-2"><%= event.name %></p>
    <% end %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-danger">
    <%= link_to root_path, class: "navbar-brand" do %>
    <h4 class="title text-light"><span class="events-logo">Private Events</span></h4>
    <% end%>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
    <% if user_signed_in? %>
       <div class="navbar-nav">
          <button class="btn btn-md text-light">SignedIn As: <strong class="text-info"><%= current_user.name %></strong></button>
          <%= link_to "My Events", user_path(current_user), class: "btn btn-md text-light", title: 'Click to Sign Out' %>
          <%= link_to "Create Event", new_event_path, class: "btn btn-md text-light", title: 'Click to New Event' %>
          <%= link_to "Explore Events", events_path, class: "btn btn-md text-light", title: 'Click to My Events' %>
          <%= link_to "Sign Out", sign_out_path, class: "btn btn-md text-light", title: 'Click to Sign Out' %>
       </div>
    <% else %> 
       <div class="navbar-nav">
          <%= link_to "Sign In", sign_in_path, class: "btn text-light btn-md mr-3 text-light", title: 'Sign In to your account' %>
          <%= link_to "Sign Up", sign_up_path, class: "btn text-light btn-md text-light", title: 'Create account' %>
       </div>
    <% end %>
 </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# meta tag for responsiveness. %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%# Dynamic page title %>
    <title><%= content_for?(:title) ? yeild(:title) : "PrivateEvents"%></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "PrivateEvents"%>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
    <header>
      <%= render 'layouts/nav'%>
    </header>

    <% flash.each do |name, message| %>
      <div class="<%= name %> text-center bg-light"><%= message %></div>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/users/_form.html.erb
<div class="container">
  <%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control" %>
    </div>

  <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container">
  <h1 class="text-info mx-3">New User</h1>

  <%= render 'form', user: @user %>

  <%= link_to 'Back', root_path, class: "btn btn-info mt-3 mx-3" %>
</div>

app/views/users/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-sm">
      <h3 class="text-info">My Created Events:</h3>
      <% @created_events.each do |event| %>
        <div class="card">
          <div class="card-body">
            <h4 class="card-title"><%= link_to event.title, event_path(event), class: "text-dark" %></div>
          </div>
          <div class="card-footer">
            <p class="card-text">Venue: <small class="text-info"><%= event.venue %></small></p>
            <p class="card-text">Date: <small class="text-info"><%= event.date %></small></p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-sm mb-3">
      <h3 class="text-info">Upcoming Events:</h3>
      <% @upcoming_events.each do |event| %>
        <div class="card">
          <div class="card-body">
            <h4 class="card-title"><%= link_to event.title, event_path(event), class: "text-dark" %></div>
          </div>
          <div class="card-footer">
            <p class="card-text">Venue: <small class="text-info"><%= event.venue %></small></p>
            <p class="card-text">Date: <small class="text-info"><%= event.date %></small></p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-sm mb-3">
      <h3 class="text-info">Past Events:</h3>
      <% @previously_attended_events.each do |event| %>
        <div class="card">
          <div class="card-body">
            <h4 class="card-title"><%= link_to event.title, event_path(event), class: "text-dark" %></div>
          </div>
          <div class="card-footer">
            <p class="card-text">Venue: <small class="text-info"><%= event.venue %></small></p>
            <p class="card-text">Date: <small class="text-info"><%= event.date %></small></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>